name: diaxi-training-tools

channels:
    - pytorch
    - nvidia
    - conda-forge

dependencies:
    - python =3.8
    - pip
    - opencv
    - pytorch >=1.8
    - torchvision
    - torchaudio
    - pytorch-cuda =11.7

    - pip:
        - -r requirements.txt
